version: "3.8"

volumes:
  db-data:

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  fusionauth:
    container_name: ${COMPOSE_PROJECT_NAME}-fusionauth
    extends:
      file: docker-compose.base.yml
      service: fusionauth
    ports:
      - 9011:9011

